# ML LAB DAY 5
#### Programmed By Sravanth Chowdary Potluri CS20B1006
1.Perform Fisher Discriminant Analysis on pima-indians-diabetes.csv
2. Perform Decision Tree classification on pima-indians-diabetes.csv
3. Perform Fisher Discriminant Analysis on pima-indians-diabetes.csv and then perform decision tree classification. compare the results.

In [127]:
# importing required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [128]:
# reading the dataset
data = pd.read_csv('pima-indians-diabetes.csv')

In [129]:
# printing the dataset
print(data)

     Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0             6         148          72          35           0        33.6   
1             1          85          66          29           0        26.6   
2             8         183          64           0           0        23.3   
3             1          89          66          23          94        28.1   
4             0         137          40          35         168        43.1   
..          ...         ...         ...         ...         ...         ...   
763          10         101          76          48         180        32.9   
764           2         122          70          27           0        36.8   
765           5         121          72          23         112        26.2   
766           1         126          60           0           0        30.1   
767           1          93          70          31           0        30.4   

     Unnamed: 6  Unnamed: 7  Unnamed: 8  
0        

In [130]:
# seperating the labels
labels = data['Unnamed: 8']
# Dropping the labels from the dataset
data = data.drop('Unnamed: 8', axis = 1)
print(data)
print(labels)

     Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0             6         148          72          35           0        33.6   
1             1          85          66          29           0        26.6   
2             8         183          64           0           0        23.3   
3             1          89          66          23          94        28.1   
4             0         137          40          35         168        43.1   
..          ...         ...         ...         ...         ...         ...   
763          10         101          76          48         180        32.9   
764           2         122          70          27           0        36.8   
765           5         121          72          23         112        26.2   
766           1         126          60           0           0        30.1   
767           1          93          70          31           0        30.4   

     Unnamed: 6  Unnamed: 7  
0         0.627      

In [131]:
# normalizing the data in the dataset
data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(data)

     Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0      0.352941    0.743719    0.590164    0.353535    0.000000    0.500745   
1      0.058824    0.427136    0.540984    0.292929    0.000000    0.396423   
2      0.470588    0.919598    0.524590    0.000000    0.000000    0.347243   
3      0.058824    0.447236    0.540984    0.232323    0.111111    0.418778   
4      0.000000    0.688442    0.327869    0.353535    0.198582    0.642325   
..          ...         ...         ...         ...         ...         ...   
763    0.588235    0.507538    0.622951    0.484848    0.212766    0.490313   
764    0.117647    0.613065    0.573770    0.272727    0.000000    0.548435   
765    0.294118    0.608040    0.590164    0.232323    0.132388    0.390462   
766    0.058824    0.633166    0.491803    0.000000    0.000000    0.448584   
767    0.058824    0.467337    0.573770    0.313131    0.000000    0.453055   

     Unnamed: 6  Unnamed: 7  
0      0.234415    0.

/Users/parzival979/miniforge3/envs/ML_LAB_5/lib/python3.10/site-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.min(axis=None) will return a scalar min over the entire DataFrame. To retain the old behavior, use 'frame.min(axis=0)' or just 'frame.min()'
  return reduction(axis=axis, out=out, **passkwargs)
/Users/parzival979/miniforge3/envs/ML_LAB_5/lib/python3.10/site-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.max(axis=None) will return a scalar max over the entire DataFrame. To retain the old behavior, use 'frame.max(axis=0)' or just 'frame.max()'
  return reduction(axis=axis, out=out, **passkwargs)


In [132]:
# splitting the dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size = 0.3, random_state = 42)

In [133]:
# performing decision tree classification
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=2)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [134]:
# predicting the test set results
y_pred = dt.predict(X_test)


In [135]:
# printing the accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7186147186147186


In [136]:
# printing the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[139  12]
 [ 53  27]]


In [137]:
# performing LDA on the dataset
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components = 1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [138]:
print(X_train)
print(X_test)

[[-1.65117210e+00]
 [-4.10235066e-01]
 [ 5.65450211e-01]
 [ 7.34716355e-02]
 [ 4.38611397e-01]
 [-1.03282167e+00]
 [-7.93300575e-02]
 [ 1.19775865e-01]
 [ 1.13250053e+00]
 [-9.14987639e-01]
 [-1.51061542e+00]
 [ 7.03966915e-01]
 [-9.23635140e-01]
 [-5.02915022e-01]
 [ 9.85000759e-02]
 [ 1.69999127e+00]
 [-1.05477025e+00]
 [ 2.34243170e-01]
 [-3.20924590e-01]
 [-5.11183579e-01]
 [-3.92634003e+00]
 [ 1.16254154e+00]
 [-1.39176610e+00]
 [-4.18239592e-01]
 [ 1.29907248e+00]
 [-7.34168726e-01]
 [ 3.81037918e-01]
 [-9.27165700e-01]
 [-1.31508011e+00]
 [ 8.59977647e-01]
 [ 5.25679839e-01]
 [-6.60768042e-01]
 [-1.86379427e+00]
 [-4.68582119e-01]
 [-1.05780651e+00]
 [ 3.07260435e-01]
 [-2.36989378e-01]
 [-1.52704414e+00]
 [ 3.87388040e-02]
 [-4.80770567e-01]
 [-3.55399904e-01]
 [ 1.29111444e+00]
 [ 1.10183972e+00]
 [ 2.88373019e-01]
 [-7.21669095e-01]
 [-1.15821553e+00]
 [ 1.15552281e+00]
 [-7.58356960e-01]
 [-6.23338126e-01]
 [-1.06239894e-01]
 [ 1.53570364e+00]
 [ 1.98692436e+00]
 [ 2.7427607

In [139]:
# assigning the outcomes for the transformed dataset based on the positive and negative of X_test
y_pred = []
for i in range(len(X_test)):
    if X_test[i] > 0:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [140]:
# printing the predicted outcomes
print(y_pred)

[0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]


In [141]:
# printing the actual outcomes
print(y_test)

668    0
324    0
624    0
690    0
473    0
      ..
619    1
198    1
538    0
329    0
302    0
Name: Unnamed: 8, Length: 231, dtype: int64


In [142]:
# calculating the accuracy of the model
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.696969696969697


In [143]:
# printing the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[100  51]
 [ 19  61]]


In [144]:
# performing decision tree classification
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=2)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [145]:
# predicting the test set results
y_pred = dt.predict(X_test)

In [146]:
# printing the accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7662337662337663


In [147]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[136  15]
 [ 39  41]]


### it is clearly evident that the combined use of LDA and Decision tree classification leads to higher accuracy